# Generated by Django 6.0 on 2026-01-04 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='tradingview_symbol',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='holding',
            name='average_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=1000000.0, max_digits=15),
        ),
    ]
