# Generated by Django 6.0 on 2026-01-04 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_stock_tradingview_symbol_alter_holding_average_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='holding',
            name='stoploss_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='holding',
            name='target_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
