# Generated by Django 6.0 on 2026-01-05 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_holding_stoploss_price_holding_target_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='deposit_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='stock',
            name='ai_signal',
            field=models.CharField(default='NEUTRAL', max_length=20),
        ),
        migrations.AddField(
            model_name='stock',
            name='signal_message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
