# Generated by Django 6.0 on 2026-01-09 10:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_transaction_order_type_transaction_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BotPortfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('is_active', models.BooleanField(default=False)),
                ('stop_loss_percent', models.DecimalField(decimal_places=2, default=2.0, max_digits=5)),
                ('take_profit_percent', models.DecimalField(decimal_places=2, default=5.0, max_digits=5)),
                ('max_trades_per_day', models.IntegerField(default=5)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bot_portfolio', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BotLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=255)),
                ('log_type', models.CharField(default='INFO', max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('bot_portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.botportfolio')),
            ],
        ),
        migrations.CreateModel(
            name='BotHolding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
                ('buy_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.stock')),
                ('bot_portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bot_holdings', to='core.botportfolio')),
            ],
        ),
    ]
