# Generated by Django 6.0 on 2026-01-09 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_botportfolio_botlog_botholding'),
    ]

    operations = [
        migrations.AddField(
            model_name='botportfolio',
            name='selected_stocks',
            field=models.TextField(default='[]'),
        ),
    ]
