# Generated by Django 6.0 on 2026-01-09 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_botportfolio_selected_stocks'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('summary', models.TextField(blank=True, null=True)),
                ('stock_symbol', models.CharField(blank=True, max_length=20, null=True)),
                ('ai_signal', models.CharField(default='NEUTRAL', max_length=20)),
                ('source_link', models.URLField(blank=True, max_length=500, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
            ],
        ),
    ]
